# Purple ricing to accompany the zsh prompt (text 90 / accent 141)
set -g status-style 'bg=colour90,fg=colour231'
set -g window-status-current-style 'fg=colour231'
set -g window-status-style 'fg=colour231'
set -g status-left-style 'fg=colour231,bold'
set -g pane-border-style 'fg=colour90'
set -g pane-active-border-style 'fg=colour141'
set -g message-style 'bg=colour141,fg=colour16'
set -g mode-style 'bg=colour141,fg=colour16'
